### ISSUE TITLE
[message] Thanks for sharing + a presets manager...

### ISSUE THREAD

**Issue by moebiussurfing** [pierrextardif/ofxShaderGlitch#1]
Hey @pierrextardif ,

Thanks a lot for sharing. The fx looks really nice. 
I must check how looks on a video and to look deep into settings/readme to better understanding.

Just in case... I have a custom presets manager that I have not made it public yet. 
But if you are interested in testing, I can prepare it and make it public.
(You can check the API on the /example2 on my fork if you like.) 

Some features:

* It handles all nested ofParameterGroup with some favorites on a clickable (and key trig) presets panel.
* Optional ImGui based files browser to store/recall any preset from a file folder.
* Some helper tools to erase/clone/copy presets on favorites.
* Randomized timer to jump between presets.

![screenshot2](https://user-images.githubusercontent.com/2106149/83354977-be065600-a332-11ea-90ac-6f993ca9a847.PNG)

**Comment by pierrextardif** [comment]
Ouh, that's cool!
Thanks!

Yeah do that please!!

Also I believe you can add as many people in a private repo now, so up to you..

++

P

PS: also I will close this.
